services:
  luckypack_universal:
    build:
      context: /srv/luckypack/App
      dockerfile: Dockerfile        # <── было Dockerfile.app
      target: prod
    image: app-luckypack_universal
    container_name: luckypack_universal
    working_dir: /app
    env_file:
      - /srv/luckypack/.env
    volumes:
      - /srv/luckypack/data:/srv/luckypack/data
      - /srv/luckypack/logs:/app/logs
      - /srv/luckypack/App/LuckyPricer/data:/app/LuckyPricer/data
    command: ["python3", "-u", "/app/LuckyBot/main.py"]
    restart: unless-stopped
    labels:
      - "keep=true"
